# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dictionary.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dictionary(object):
    def setupUi(self, Dictionary):
        Dictionary.setObjectName("Dictionary")
        Dictionary.resize(1000, 600)
        Dictionary.setStyleSheet("font: 25 14fpt \"Verdana Pro Light\";\n"
        "background-color: rgb(47, 79, 79);\n"
        "color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(Dictionary)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.enter_topic = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_topic.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.enter_topic)
        self.add_dictionary_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_dictionary_btn.setStyleSheet("background-color: rgb(34, 57, 57);")
        self.add_dictionary_btn.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.add_dictionary_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 413, 281))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topic_list_show = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.topic_list_show.setStyleSheet("font-size: 16pt")
        self.topic_list_show.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.topic_list_show)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.back_btn.setStyleSheet("background-color: rgb(34, 57, 57);")
        self.back_btn.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.back_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Dictionary.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dictionary)
        QtCore.QMetaObject.connectSlotsByName(Dictionary)

    def retranslateUi(self, Dictionary):
        _translate = QtCore.QCoreApplication.translate
        Dictionary.setWindowTitle(_translate("Dictionary", "MainWindow"))
        self.add_dictionary_btn.setText(_translate("Dictionary", "Добавить словарь"))
        self.back_btn.setText(_translate("Dictionary", "Вернутся на главное меню"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dictionary = QtWidgets.QMainWindow()
    ui = Ui_Dictionary()
    ui.setupUi(Dictionary)
    Dictionary.show()
    sys.exit(app.exec_())
