# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teach.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setStyleSheet("font: 25 14pt \"Verdana Pro Light\";\n"
                                 "background-color: rgb(47, 79, 79);\n"
                                 "color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.finish_btn = QtWidgets.QPushButton(self.centralwidget)
        self.finish_btn.setStyleSheet("background-color: rgb(34, 57, 57);")
        self.finish_btn.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.finish_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 13, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 12, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 14, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.progress = QtWidgets.QLabel(self.centralwidget)
        self.progress.setObjectName("label")
        self.progress.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.progress, 2, 1, 1, 1)
        self.word_show = QtWidgets.QLabel(self.centralwidget)
        self.word_show.setStyleSheet("background-color: rgb(255, 255, 255);"
                                "color: rgb(12, 45, 6);"
                                "font-size:14pt;"
                                "margin-left:20px;"
                                "text-align: center")
        self.word_show.setObjectName("Word")
        self.gridLayout_2.addWidget(self.word_show, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 4, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enter_answer = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_answer.setFrame(True)
        self.enter_answer.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.enter_answer)
        self.next_btn = QtWidgets.QPushButton(self.centralwidget)
        self.next_btn.setStyleSheet("background-color: rgb(34, 57, 57);")
        self.next_btn.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.next_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 10, 1, 1, 1)
        self.message = QtWidgets.QLabel(self.centralwidget)
        self.message.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.message, 5, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 437, 16))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.finish_btn.setText(_translate("MainWindow", "Закончить"))
        self.progress.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Прогресс</p></body></html>"))
        self.word_show.setText(_translate("MainWindow", "<html><p> </p>< / html > "))
        self.next_btn.setText(_translate("MainWindow", "Ввод"))
        self.message.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Введите перевод</p></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
